2018-12-13 14:53:06
local variable 'worksheet' referenced before assignment

2018-12-13 14:54:06
local variable 'worksheet' referenced before assignment

2018-12-13 14:55:46
append_row() takes from 2 to 3 positional arguments but 5 were given

2018-12-13 15:01:39
Unable to find the server at oauth2.googleapis.com

2018-12-13 15:02:24
Unable to find the server at oauth2.googleapis.com

2018-12-13 15:03:04
Unable to find the server at oauth2.googleapis.com

2019-01-10 14:18:45
Unable to find the server at oauth2.googleapis.com

2019-01-10 14:19:49
Unable to find the server at oauth2.googleapis.com

2019-01-17 14:43:29
name 'lsm303' is not defined

2019-01-17 14:56:12
append_row() takes from 2 to 3 positional arguments but 11 were given

2019-01-17 15:00:57
[Errno 121] Remote I/O error

2019-01-17 15:23:03
Unable to find the server at oauth2.googleapis.com

2019-01-30 14:33:10
'NoneType' object has no attribute 'append_row'

2019-01-30 14:40:14
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "internalError",
    "message": "Internal Error. User message: \"An internal error has occurred which prevented the sharing of these item(s): [PI_DATA] 2019-01-30 14:40:14\""
   }
  ],
  "code": 500,
  "message": "Internal Error. User message: \"An internal error has occurred which prevented the sharing of these item(s): [PI_DATA] 2019-01-30 14:40:14\""
 }
}


